### ISSUE TITLE
Provide more context around items under editorial review

### ISSUE THREAD

**Issue by justinwb** [solid/process#104]
Creating this issue to track a comment @Mitzi-Laszlo [raised in solid/process#95](https://github.com/solid/process/pull/95#issuecomment-519997883).

> What would be great to include as well is:
> the aim/ scope of the specification
> the aim/ scope of the roadmap
> the aim/ scope of the documentation
> the respective repositories to which proposals in the form of pull requests to the specification, roadmap, and documentation should be made
> the aim of each repo and how it connects to this process

Am tracking this separately since it would expand quite a bit the scope of the solid/process#95 when it's near the end of the review cycle. Any work towards this can go in new branch / pull.

**Comment by justinwb** [comment]
Note that in the latest commits under pull solid/process#95, each repository across specification, roadmap, and documentation is broken out with a short description. For the specification, primary documents (as they exist right now) have also been specifically identified. As more emerge, they'll be updated. 

I think then, that this covers:

- the respective repositories to which proposals in the form of pull requests to the specification, roadmap, and documentation should be made

The remaining question then is whether these other points aren't better left to the individual repositories to explain:
- the aim/ scope of the specification
- the aim/ scope of the roadmap
- the aim/ scope of the documentation

This point maybe is somewhere in the middle:
- the aim of each repo and how it connects to this process

**Comment by justinwb** [comment]
@Mitzi-Laszlo Based on the description of repositories that now lives in [editors.md](https://github.com/solid/process/blob/master/editors.md), have we made progress towards any of these points?

**Comment by Mitzi-Laszlo** [comment]
This takes care of defining the repositories for each https://github.com/solid/process/pull/83
