### ISSUE TITLE
Omit email addresses

### ISSUE THREAD

**Issue by csarven** [solid/process#113]
Can we omit email addresses from panel.md? Perhaps mention our WebIDs instead?

**Comment by TallTed** [comment]
WebIDs don't (though they arguably ought to) always lead to a usable contact method. In my experience, email is the most consistently reliable method, though also imperfect. Indeed, your own WebID leads to your email address, so you're just adding an extra click to someone's effort to contact you.

What's your reason to make this change?

**Comment by csarven** [comment]
I agree with you. They are all useful in different contexts. Here we are on a webpage; no WebID or email involved. We are on Gitter, W3C mailing list and IRC, audio/video meetings, and so forth. Someone somehow arrived here.

Removing email addresses at the very least minimises information clutter. Less social pressure to provide one. Just as we are putting some pressure on people to agree to GitHub, Gitter's, W3C's.. terms of services in order to participate.

**Comment by Mitzi-Laszlo** [comment]
Let's make it optional, everyone who wants their email address removed please submit a pull request.
