### ISSUE TITLE
For what purposes should administrator privileges be used?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#128]
Tag: question (not available in this repo)

The README says that:

> Administrators are granted privileged access to control the tools, systems, and services used for advancing the Solid Specification, Solid Roadmap, and Supporting Documentation. This includes the Solid GitHub organization, Solid Gitter channels, the Solid Forum, and the Solid Website.

It's clear that we definitely need administrators for tasks such as giving people access etc.

However, especially after #127, I think we need a discussion about the exact scope of the administrator mandate.

Specifically, even though admin privileges necessarily come with write access to all repositories, it seems that it is strongly undesired that administrators write to arbitrarily repositories. That is, assuming no other role in a given repository, they should probably follow the process of that repository and create PRs like any external person would, and wait for the responsible/editor/… of the repository to take up those PRs.

I have in the past seen edits to various repositories (typically small ones to READMEs etc.), but this feels intrusive. Repositories should have autonomy, and every actor in the ecosystem, including admins, should respect that. The exception being old/abandoned/… repositories, since these do not have such autonomy, so it is reasonable that an admin steps in when needed.

Note in particular that the README does not provide any role for administrators.

Assigned the current administrators to discuss.

**Comment by justinwb** [comment]
> Specifically, even though admin privileges necessarily come with write access to all repositories, it seems that it is strongly undesired that administrators write to arbitrarily repositories.

Agree! The scope of the administrator role is purely operational. Solid needs administrators to manage accounts, access, infrastructure, etc. For example, the accounts and systems that host the website, domains, mail, associated infrastructure, and source control. Administrators have access to all repositories as part of the Admin level permissions in [Github's scheme](https://help.github.com/en/articles/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level), but that access should only be wielded for operational/administrative things, such as managing organizational configurations, creating/transferring/archiving repositories, managing teams and permissions to adhere to the settings defined in the process documentation, etc. Administrators aren't meant to police, create, or modify content. That is left to other roles. If the current process isn't clear enough on this point then we should update it to be more explicit.
