### ISSUE TITLE
Create notifications-panel repository

### ISSUE THREAD

**Issue by csarven** [solid/process#131]
As per https://github.com/solid/process/blob/master/panels.md#notifications-panel , we need a repository at https://github.com/solid/notifications-panel

**Comment by Mitzi-Laszlo** [comment]
Would [this existing repository](https://github.com/solid/solid-notifications ) possibly be a good working place for the Notifications Panel?

**Comment by csarven** [comment]
I don't think so. That repository is an unfinished implementation of LDN. So, at the very least it would require the existing work to be wiped or changing the intention/semantics in order to run the panel. I wouldn't recommend doing that.

**Comment by justinwb** [comment]
> I don't think so. That repository is an unfinished implementation of LDN. So, at the very least it would require the existing work to be wiped or changing the intention/semantics in order to run the panel. I wouldn't recommend doing that.

Agree - more appropriate to create a clean notifications panel repository associated with the panel.

**Comment by justinwb** [comment]
Panel [created](https://github.com/solid/notifications-panel). Panel team [created](https://github.com/orgs/solid/teams/notifications-panel/) and added to the repo with Maintain permissions.
