### ISSUE TITLE
Consider panel dependencies and perhaps adjust timing

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#135]
In general, I am a supporter of the creation of panels.
However, I think that the sudden proliferation of panels is creating problems.

First of all, there are now so many panels happening in parallel that it is unfeasible for any single person to be aware of the work going on in all of them. This means that we are lacking coordination, and that common themes or problems are less likely to be caught. It also means that we are limiting the work that Solid experts can do, since their efforts are either spread across many panels, or necessarily restricted to certain ones.

Second, we have no dependency tracking. This means that some panels are simply not ready to start, given that some of the core components they need are not developed yet.

We might need to reconsider the timing in which panels are being started. Right now, we have started 10+ panels all at once, which seems to much given the number of people and number of dependencies.

In any case, we need to make the dependencies between panels explicit, so that we can take them into account for temporal and capacity planning.

**Comment by RubenVerborgh** [comment]
Case in point: https://github.com/solid/app-authorization-panel/issues/33

**Comment by justinwb** [comment]
I agree that we need overarching focus and coordination, and I think that we can work within the structures that we’ve got now to guide and encourage that work - and achieve the milestones that are most important to Solid (chiefly the v1.0 specification). 

I believe that part of the responsibility of the editorial team is to be proactive in providing this guidance and coordination, so I'm going to propose a project under the scope of https://github.com/solid/specification, primarily assigned to editors, to undertake this.

**Comment by Mitzi-Laszlo** [comment]
In practice the authentication, interoperability, and authorisation panel are the only active panels. Let's create a one stop shop page on the W3C Wiki with an overview of panel calls to make it easy for everyone to keep track.

**Comment by Mitzi-Laszlo** [comment]
Also, perhaps it's an idea to close inactive panels for now.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/208
