### ISSUE TITLE
Data Interoperability & Data Portability 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#145]
In the editorial assignments the themes "data portability" and "data interoperability" are separate: https://github.com/solid/process/blob/master/editors.md#data-interoperability 

In the panels there is only a theme "data interoperability" however sometimes data portability is discussed. 

I propose to change the name of the editorial assignments and panel into "data interoperability and portability" because: 

* It clarified which editorial assignment reviews proposals from which panel 
* splitting the themes into to panels would mean the panels would be very small and members very similar

**Comment by justinwb** [comment]
Personally I don't have any issues with this, but am going to share this ticket now with the rest of the panel and give them a chance to raise any concerns of their own. If we can revisit this at the end of the week, that should give ample time to surface any vehement objections.

**Comment by DoctorBud** [comment]
I'm very new to all of this Solid and am probably lacking context, but after reading the definitions at https://github.com/solid/process/blob/master/editors.md#data-interoperability and https://github.com/solid/process/blob/master/editors.md#data-portability, it seems like the Interoperability refers to the way that one process/agent might try to access a subset of a POD's data via the REST API. On the other hand, the Portability idea is about me (who owns my data) being able to confidently move that data to another provider that I choose, and I'd probably do that via some sort of bulk export.

So I'm not certain they have the same problems, users, or solutions. But merging the two missions might still be very practical, if the distinction between Interopability and Portability is kept in mind.

**Comment by DoctorBud** [comment]
More briefly:
- Interoperability supports Sharing, by allowing my data to be accessible to others.
- Portability prevents Lock-in, by allowing me to move my data to a different provider
These seem to be orthogonal concerns.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/156
