### ISSUE TITLE
Cryptography & Security 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#146]
In the editorial assignments the themes "Cryptography" and "Security" are separate: https://github.com/solid/process/blob/master/editors.md#cryptography

In the panels there is only a theme "Cryptography (Signing and Encryption)": https://github.com/solid/process/blob/master/panels.md#cryptography-signing-and-encryption

I propose to have two panels "Cryptography" and "Security" or to merge the editorial assignments into "Cryptography and Security" 

I propose to change the name of the editorial assignments and panel into "data interoperability and portability" because it clarifies which editorial assignment reviews proposals from which panel.

**Comment by justinwb** [comment]
> I propose to have two panels "Cryptography" and "Security" or to merge the editorial assignments into "Cryptography and Security"

There's definitely overlap between these two categories, but there's also some significant differences. Not every cryptographer is an expert in network / system / application security, or vice versa. I think that there's plenty of room to establish groups focused in each area that are independent of each other.

That said, it may be that for the time being we're trying to reduce the number of topics, and (maybe consequently) the number of panels, until we have more unique representation across them. If that's the case, then we could consider joining these together. I'd be interested @dmitrizagidulin's take from the crypto/signing/encryption side.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/blob/master/panels.md#privacy-and-individuals-rights-protection-panel this panel is definitely different but considering there is one panellist and the themes overlap it might be an idea to incorporate the work into a single panel for now. If it gets unwieldy when too many people join the panel we can always reconsider.

**Comment by maxidorius** [comment]
I'm fine with merging. I agree there is a lot of overlap in those areas.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/157
