### ISSUE TITLE
Test Suite not really a Panel 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#150]
The test suite is in a separate repository from the specification so it could be interpreted as falling outside of the editorial process. 

Although there is a test suite panel, there is no corresponding editorial assignment so it is unclear who would review proposals from the test suite panel. 

One solution could be to have an independent group from the editorial process working on the test suite which is based on the specification produced by the editorial process.

**Comment by jaxoncreed** [comment]
Agreed. It isn't a panel. But we still have meetings, so we need to report those meetings somewhere even if it's just myself and @kjetilk for now.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/161

**Comment by Mitzi-Laszlo** [comment]
Perhaps in the process readme?

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/162
