### ISSUE TITLE
Determine the license for this repository and its documents

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#155]

**Comment by Mitzi-Laszlo** [comment]
("this" repository = specification repository)

Relevant to other GitHub Solid repositories too.

**Comment by justinwb** [comment]
See this decision by @timbl that I think would also apply to this as well - https://github.com/solid/process/issues/103

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/specification/blob/master/LICENSE.md
