### ISSUE TITLE
Solid Conversations 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#168]
There are a few different chat channels for conversations about Solid that have evolved organically. Here's a shot at looking at mapping the channel purposes and trying to make sure that the content doesn't get diluted over many channels while still allowing for software diversity. 

Gitter seems to be used for Solid specification development.

 In particular the following channel is a place for all panellists and editors to meet: 
* [specifcation](https://gitter.im/solid/specification?source=orgpage) 

There are a few gitter channels for specific panels focused on authoring proposals for the Solid specification. 
* [security-cryptography-and-privacy](https://gitter.im/solid/cryptography-security-and-privacy#)
* [app-authoriisation-panel](https://gitter.im/solid/app-authorization-panel?source=orgpage)
* [authentication panel](https://gitter.im/solid/authentication-panel?source=orgpage)
* [data-interoperability-panel](https://gitter.im/solid/data-interoperability-panel?source=orgpage)

The test suite conversations are also very focused on: 
* [test-suite](https://gitter.im/solid/test-suite?source=orgpage)

Now there is a channel for the Creators to talk about solid project.org development including documentation for the Solid specification: 
* [solidproject.org](https://gitter.im/solid/solidproject.org?source=orgpage)

Until now all the conversation is happening on gitter. 

Now we enter the areas where conversations start to double up. In particular there are two main places for Solid conversations: forum.solidproject.org and Solid gitter which are overlapping meaning that that sometimes people interested in the same material are not meeting. 

# Overlap 
There are a few gitter channels talking about solid specification implementation: 
* [pods](https://gitter.im/solid/pods?source=orgpage)
* [app development](https://gitter.im/solid/app-development?source=orgpage)
* [chat-app](https://gitter.im/solid/chat-app?source=orgpage)
* [node-solid-server](https://gitter.im/solid/node-solid-server?source=orgpage)
* [data browser](https://gitter.im/solid/data-browser?source=orgpage)

There are often doubled up on on https://forum.solidproject.org/categories meaning that all channels are diluted. 
Similarly Solid Events conversations are happening on both the forum and gitter
* [solid-events](https://gitter.im/solid/solid-events?source=orgpage)

My proposal is to phase out gitter as a place to talk about implementation and focus on solid specification development because it is linked to GitHub where the specification development is happening. 

# Unknown Purpose
There are a few gitter channels that are already covered including: 
* [solid-spec](https://gitter.im/solid/solid-spec?source=orgpage) now "specification" 
* [site-and-docs](https://gitter.im/solid/site-and-docs?source=orgpage) now "solidproject.org"

My proposal is to delete these channels so that the energy gets concentrated into one place unless there are reasons for keeping two channels with the same purpose. 

The following chat channels don't have a clearly stated focus at the moment  If you use the chat channel regularly and know the focus please do say. 
* [solid-git](https://gitter.im/solid/solid-git?source=orgpage)
* [suggestions](https://gitter.im/solid/suggestions?source=orgpage)
* [community](https://gitter.im/solid/community?source=orgpage)
* [introductions](https://gitter.im/solid/introductions?source=orgpage)
* [Solid Chat](https://gitter.im/solid/chat?source=orgpage) 

Although Solid chat seems to be a landing place, I think that solidproject.org should cover a lot of the early questions. 

This is really just a first shot on my understanding so please do suggest improvements and let me know if you are using these channels in ways that are not mentioned here.

**Comment by sideshowtom** [comment]
The work going on in the panels is very exciting and they are addressing a lot of fundamental things.  It would be great to be able to follow and search all those conversations including the double backs and blind alleys, because that really helps us slowpokes to get an understanding of the issues.

**Comment by sideshowtom** [comment]
Yes this is frustrating.  I think there is a trade off between making discussions accessible and getting people who don't seem to really want to be accessible to participate in accessible discussions.

The work going on in the panels is very exciting and it would be great to have it in a form where its searchable and accessible in one place.

Long term of course it would be best to have chats on solid pods with fancy features like multiple threads with different permission levels and categories, but thats a long way from ready imho.
