### ISSUE TITLE
Libraries 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#169]
There are several people working on building libraries for Solid and no description of how they should work together in the process repository. 

A panel is specifically for making proposals to the Solid specification for editorial review so a panel is not quite adequate. 

Possibly a solution would be to have a section in the README of the process similar to [solidproject website](https://github.com/solid/process#solidprojectorg-website) or [test suite](https://github.com/solid/process/pull/162) that describes the aim and where to list yourself if you choose to work in the Solid GitHub. 

For example: 

# Solid Libraries 
Anyone can write a Solid library based on the Solid specification. You can find an overview of Solid libraries in the the [libraries repository](https://github.com/solid/libraries/blob/master/README.md). Librarians(link to GitHub.com/process/librarians.md) are responsible for keeping the overview of Solid libraries up to date as well as the libraries that can be found in the Solid GitHub account.

**Comment by jeff-zucker** [comment]
There is definitely a need to have a central place for information on libraries.  Putting a link within "process" is good in terms of alerting developers how to create a library but I think there needs to be a separate landing page telling developers what libraries are available, what the differences in capabilities and interfaces are, and why they might use one or another.   In other words a page devoted to using libraries, not creating them.  Perhaps something like:

### Solid Libraries and Tools

There are a number of Solid libraries and toolkits which allow developers to create apps without having to re-invent the wheel on basic operations.  These include RDF parsing toolkits, login and authentication libraries, file-handling libraries, and GUI toolkits and component libraries.  An overview and comparision of libraries and toolkits may be found at X,  A cheatsheet of how-to perform basic operations in different libraries may be found at Y,  A list of library and toolkit developers may be found at. Z,

**Comment by jeff-zucker** [comment]
I would be willing to take the lead on organizing/expanding the library pages but it would be great to have a team of other developers.  If not a panel, then what?  There should be specified comm channels and a central place people can follow developments.

Currently, I know of four places libraries are discussed.  Are there others?

https://github.com/solid/libraries

https://github.com/solid/information/blob/master/documentation/developer-tools.md

https://vincenttunru.gitlab.io/tripledoc/docs/cheatsheet

https://github.com/inrupt/solid-lib-comparison

**Comment by Mitzi-Laszlo** [comment]
Fantastic! This would be really valuable @jeff-zucker 

On second thought the overview could be done on solid.github.io repo so that it links to the website directly. @jeff-zucker maybe you could apply to be a Creator by submitting a pull to the process repo if you're interested?

The the Librarians could be added to the process readme:  

#Solid Libraries

Anyone can write a Solid library based on the Solid specification. Librarians(link to GitHub.com/process/librarians.md) are responsible for keeping the  libraries that can be found in the Solid GitHub account up to date.

**Comment by Mitzi-Laszlo** [comment]
"Librarians communicate via gitter/solid/librarians"?

**Comment by michielbdejong** [comment]
Thanks for picking this up @jeff-zucker! Yes, I think those four resources should probably be merged into one.

**Comment by michielbdejong** [comment]
I think I found a fifth one: https://github.com/solid/solid-platform#libraries

**Comment by michielbdejong** [comment]
Also https://forum.solidproject.org/t/soukai-a-different-way-to-query-pods/2105 should be added to the new list.

**Comment by jeff-zucker** [comment]
Thanks, @michielbdejong .  I've added that and a number of others at https://github.com/jeff-zucker/solid-libraries.

**Comment by Mitzi-Laszlo** [comment]
Amazing! Thanks @jeff-zucker this is really fantastic. @Vinnl @NSeydoux could you integrate this content into the website draft?

**Comment by Vinnl** [comment]
It's on my todo list, but so are many other things unfortunately. It would go [here](https://github.com/solid/solid.github.io/blob/master/_posts/for-developers/apps/tools/2019-01-01-00_overview.md), I think.

**Comment by michielbdejong** [comment]
This issue is resolved by the combination of https://github.com/solid/solid.github.io/pull/191 + https://github.com/jeff-zucker/solid-libraries/pull/6 + https://github.com/solid/information/pull/302 + https://github.com/solid/solid-platform/pull/7
