### ISSUE TITLE
as raised in PR #293, copyright notices should comply with standard form

### ISSUE THREAD

**Issue by TallTed** [solid/process#178]
Phrases like "copyright 2018 - present" have been used in many documents.  This is not correct for copyright notices, which require explicit numbers for relevant years. 

Also, copyright notices must identify the entity claiming that copyright.

@Mitzi-Laszlo has suggested in the (closed‽) solid/information#293 that (Inrupt? the ephemeral "Solid"?) "[we] get the view of a professional and adapt all the licenses accordingly so that all repos have a uniform approach".  I think that's a fine idea, and am opening this issue to track it.

**Comment by RubenVerborgh** [comment]
> Phrases like "copyright 2018 - present" have been used in many documents. This is not correct for copyright notices, which require explicit numbers for relevant years.

Do we have a reference for that? (As to which jurisdiction has that interpretation etc.?)

In any case, we probably want to tackle this with a process rather than manual intervention; like a GitHub agent that checks affected projects etc. We should also be careful not to lie: only when a repository is actually updated in (let's say) 2019, it is meaningful to change the license text.

**Comment by TallTed** [comment]
These are US Gov references, but international copyright treaties mean that they're more generally applicable -- 
* https://www.copyright.gov/circs/circ03.pdf
* https://www.copyright.gov/comp3/chap2200/ch2200-notice.pdf

"Present" *might* be interpreted with the intended meaning in some cases (which interpretation would only be made during litigation, which litigation be avoided simply by being explicit), but only if the document to which it's attached has an explicit and obvious date, which is not the case for most documents in current question -- and even then, this interpretation is not guaranteed.

The easiest way to remove any question is simply to use the explicit years, which does not seem onerous to me. Working not to do so has already cost more time than it will save.

**Comment by kjetilk** [comment]
IANAL, but my understanding is that copyright law applies without a notice, i.e. without a valid notice, all rights are reserved, i.e. ideal rights, rights to reproduce, etc. Basically, copyright law is very restrictive, there's not much other parties can do with the material we publish.

So, the real issue here is that we *grant* rights that are not granted by copyright law, and that's the reason why we need these LICENSE files, without a valid one, people have to legally assume that copyright law applies in full, which is basically a hands-off situation, which is something we can't live with, it is important for us that the documentation and code can be dissemenated.

**Comment by TallTed** [comment]
@kjetilk - Approximately, yes. 

A valid notice is not *required* for copyright to exist -- but that notice helps enable and lower the cost of enforcement of that copyright.

An *invalid* notice (whether due to malformation or other fault) does not invalidate copyright -- but makes proof thereof harder -- which makes the intended permissive licensure harder to enforce over potential false copyright claims.

**Comment by Mitzi-Laszlo** [comment]
Good idea, best submit pull requests to specific places that need to change.

**Comment by TallTed** [comment]
This is maddening. I initially submitted PR https://github.com/solid/information/pull/293, which was closed without merge by @Mitzi-Laszlo with --

> Let's get the view of a professional and adapt all the licenses accordingly so that all repos have a uniform approach.

(Of course, that repo has been archived, so that specific PR is moot, unless the specific document for which it was submitted was moved to another repo, in which case it likely still applies...)

Then, this attempt at uniformity is closed with "submit PRs to specific places to be changed."

Which is it to be?  Individual PRs, or one issue?

(Note -- My silence the past several months has been due to a medical leave of absence, not disinterest nor acquiescence to actions taken in that time.)

**Comment by justinwb** [comment]
@TallTed Thanks for re-raising this. Apologies if this was closed out without sufficient resolution. Happy to pick this back up. Looking at the original issue, this was specific to the copyright statements in the license.md files for repos under the solid org?

**Comment by TallTed** [comment]
@justinwb -- 

solid/information#293 was specifically about the `license.md` files within the Solid Project. This issue is broader, as the `license.md` files listed in the file targeted there were merely exemplars of the incorrect forms of copyright statements, which concern I had raised in several areas, generally only to be rebuffed as "not an expert" (i.e., not a copyright lawyer).

I provided links to authoritative references (https://github.com/solid/process/issues/178#issuecomment-558229488), upon which I based my PRs and related suggestions, which references were not taken as sufficiently authoritative.

Problematic copyright statements remain in [Solid](https://github.com/search?q=org%3Asolid+copyright+present&type=Code), [Inrupt](https://github.com/search?q=org%3Ainrupt+copyright+present&type=Code), and probably other related organizations. (The github search utility does not provide for a fuzzy search that will only locate the problematic text, so some non-problem files show up in the searches I've linked here.)

**Comment by csarven** [comment]
I believe we have acknowledged this issue in general and Ted has made PRs on this eg. at least in one place against the Solid specification: https://github.com/solid/specification/pull/89 . We have updated to use an actual date (in place of "present"). We should comb the rest of the Solid repos and update as suggested.

**Comment by TallTed** [comment]
I believe this issue has been resolved, at least in the decision of future action, by https://github.com/solid/specification/pull/89#issuecomment-629627951 guidance to use the W3CG copyright boilerplate.
