### ISSUE TITLE
Add query-panel repository

### ISSUE THREAD

**Issue by kjetilk** [solid/process#186]
The requirement to have a SPARQL-based patch system to the `PATCH` method, is discussed in https://github.com/solid/specification/issues/125 , but is spawning many different repositories, and also has connections to the W3C [SPARQL 1.2 CG](https://github.com/w3c/sparql-12/). 

I think we would have a more focused effort on this topic if we activate the already existing query panel. However, it extends beyond the existing solid-tpf repository, and so, I suggest we add a query-panel repository as encouraged by the current process.

**Comment by RubenVerborgh** [comment]
> However, it extends beyond the existing solid-tpf repository,

That one is just a piece of prototype code; it should probably be archived and stay as-is.

**Comment by justinwb** [comment]
The query-panel repository has been created, along with peripheral requirements (panel team, gitter channel, etc.)
