### ISSUE TITLE
Discussing solid community perceptions and structure

### ISSUE THREAD

**Issue by aschrijver** [solid/process#205]
This issue is in response of @csarven in https://github.com/solid/process/issues/202#issuecomment-630273205

That's a lot of things to answer :)

- My expection: an open well-oiled community is forming (don't know if that was the intention)
- 'Adequate engagement': if the forum is just seen as supplementary thing for some members, and core members leave their info all over the web, then that probably explains much of that feeling.
  - I think its **important** for this to be more clearly communicated to the people interacting there!
- Forum: yes, I am also not suggesting having documentation there, but in github (wiki posts _could_ be used for temporary stuff), the forum excels at communication over longer times when not everyone is 'live', and also as an archive of such communication (via search, not on archive.org unfortunately I see)
- Talking anywhere: that fragmentation also makes it harder to find those panels, keep the structure, and have interested outsiders get involved. I think people who are not Solid full-timers need a place to get overview of current status.
- Github/Gitter: as described above my Github is already incredibly crowded. I'd need to add, say 40-50 solid repo's and monitor them, but I'm no full-timer too. Most interested how Solid fits with ActivityPub. Same for gitter which is for real-time chat, mostly for fulltimers, or people that do a quick jump in now and then to ask a question. I'm not going to have a gitter window open all the time.
- Core team on the forum: Yes, when there are relevant, more thorough discussions that can't be handled in a quick chat. But aforementioned chat integration plugin would do the trick probably for you to judge by notifications when that is needed.

**Comment by justinwb** [comment]
@aschrijver It seems like the consistent vein throughout these points is that you'd like to see the forum employed more, at a minimum as a vehicle for providing communication and updates, which I think is a legitimate ask. 

In general, providing a better summary of current activities (whether they be through the forum or otherwise), is something we can improve. Appreciate you taking the time to provide this feedback - it's helpful.

**Comment by aschrijver** [comment]
Thank you. Yes, the forum seems the best tool to bring the most people on the same page in terms of communication and exchange of ideas. That includes not only the highly to moderately active ones, but _anyone_ active in other fields following Solid with interest.

**Comment by scenaristeur** [comment]
I'm pro forum too : 
it's accessible for non-dev users whereas github / gitter need to go to the issues, & understand on what repo, how to search on issues. 
It's more friendly.
I can easily find or ask.
I can not come for some days and come back and rapidly see what topics are hot whereas in gitter it's impossible to follow a discussion.

**Comment by justinwb** [comment]
@scenaristeur @aschrijver This is good food for thought. In addition to the current effort underway to see how we can [optimize panel efforts](https://github.com/solid/process/issues/202), we'll also look at how we can better factor the forum into communicating those efforts, and the efforts of the editorial team progressing the spec. If you have thoughts or suggestions on how we do this, it'd be great to hear them (lets continue to use this thread for that).

**Comment by aschrijver** [comment]
> If you have thoughts or suggestions on how we do this, it'd be great to hear them (lets continue to use this thread for that).

Or... do that on the forum. Maybe not in topic "[This forum should be central to Solid community, and not Gitter](https://forum.solidproject.org/t/this-forum-should-be-central-to-solid-community-and-not-gitter/2747/33?u=aschrijver)" where @scenaristeur already made a proposal, but in a fresh topic without the prior Gitter-related history to it.

**Comment by justinwb** [comment]
> Or... do that on the forum, or at least start it there high-level and elaborate the details in the process repo. 

Fair enough 👍  Will get something posted soon and we'll go from there.
