### ISSUE TITLE
Proposal to Clean up Repos to Avoid Wiki Rot

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#207]
On https://github.com/solid/process/issues/180 there was a conversation about a repo naming system and on https://github.com/solid/process/pull/172 there is a repository overview. 

There are 117 repositories in github.com/solid and it is not easy for newcomers nor for people working on the repositories for some time to navigate between these repositories in a way that it is crystal clear what is the aim of each of the repositories. 

The Process repository was started as an attempt to collectively agree on how to work on specific aims within github.com/solid including: administration of solid properties, standardisation work, and creating and maintaining the website solidproject.org. There are more activities going on in github.com/solid that the three just mentioned. 

This is a proposal about how to gain clarity around the aims of the work happening in github.com/solid as well as clarity around who is responsible for what. 

There are some repositories that used to fill the functions of the repositories already described here above but are no longer maintained by defined people. The key information needs to be combined with the repositories above and archived to avoid thinning of information and wiki rot.

| Repository  | What needs to happen before archiving |Where this is now taking place instead  |
| ------------- | ------------- | ------------- |
| https://github.com/solid/Explaining-the-Vision-Panel  | no action needed | Solidproject.org   |
| https://github.com/solid/webid-oidc-spec  | Move issues and pull requests to github.com/solid/specification | github.com/solid/specification  |
| https://github.com/solid/solid-spec  | Move issues and pull requests to github.com/solid/specification | github.com/solid/specification  |
| https://github.com/solid/web-access-control-spec  | Move issues and pull requests to github.com/solid/specification | github.com/solid/specification  |
| https://github.com/solid/solid  | Move issues and pull requests to github.com/solid/specification | github.com/solid/specification  |
| https://github.com/solid/solid.mit.edu | no action | solid.mit.edu no longer attached to this repo |
| https://github.com/solid/websci-2019 | no action | solidproject.org/press|
| https://github.com/solid/Roadmap |no action | solidproject.org/roadmap (ticket to be created) |
| https://github.com/solid/solid-apps | no action | solidproject.org/use-solid |
| https://github.com/solid/pods | no action | solidproject.org/use-solid |
| https://github.com/solid/solid-idp-list | no action | solidproject.org/use-solid |
| https://github.com/solid/solid-idps  | no action | solidproject.org/use-solid |
| https://github.com/solid/information  | no action | solidproject.org|
| https://github.com/solid/context | no action | solidproject.org.for-developers |
| https://github.com/solid/vocab | no action | solidproject.org.for-developers |
| https://github.com/solid/solid-namespace | no action | solidproject.org.for-developers |
| https://github.com/solid/dweb-summit-2018 | no action | solidproject.org.for-developers |
| https://github.com/solid/talks | no action | solidproject.org.for-developers |
| https://github.com/solid/intro-to-solid-slides | no action | solidproject.org.for-developers |
|https://github.com/solid/profile-viewer-tutorial | no action | solidproject.org.for-developers |
|https://github.com/solid/solid-tutorial-angular | no action | solidproject.org.for-developers |
|https://github.com/solid/solid-tutorial-rdflib.js | no action | solidproject.org.for-developers |
|https://github.com/solid/understanding-linked-data | no action | solidproject.org.for-developers |
| https://github.com/solid/solid-tutorial-pastebin | no action | solidproject.org.for-developers |
| https://github.com/solid/solid-tutorial-intro | no action | solidproject.org.for-developers |

## Solid Research

In the remaining ~50% of the repositories of github.com/solid there are a range of experiments and research on Solid. The aim of governance of the experimental research is not described in the process repository and largely started during the Solid MIT research project and has been picked up by the University of Ghent in more recent years. 

Some of the research works on implementing the Solid standard to ensure the proposals are feasible. There is not a defined intention to provide this software as a service to end-users with a defined service provider, although some users do so organically. In particular node solid server is used by many developers as a reference Pod when building Solid applications. 

Here are a list of repositories that could be tagged as 'research': 

There are various implementations of the Solid specification. 

| Implementation of Solid Specification | Associated Repositories | 
| ------------- | ------------- | 
| [Implementation of Solid Server (Pod)](https://github.com/orgs/solid/projects/2) | [node-solid-server](https://github.com/solid/node-solid-server), [node-solid-ws](https://github.com/solid/node-solid-ws) | [Jackson Morgan](https://github.com/jaxoncreed), Michiel de Jong |
| [Data Browser (app)](https://github.com/orgs/solid/projects/4) | [solid-ui](https://github.com/solid/solid-ui), [mashlib](https://github.com/solid/mashlib), [solid-panes](https://github.com/solid/solid-panes), [Chat Pane](https://github.com/solid/chat-pane), [Solid Pane Source](https://github.com/solid/solid-pane-source), [Source Pane](https://github.com/solid/source-pane), [Issue Pane](https://github.com/solid/issue-pane), [Contacts Pane](https://github.com/solid/contacts-pane), [Folder Pane](https://github.com/solid/folder-pane), [Meeting Pane](https://github.com/solid/meeting-pane), [Pane Registry](https://github.com/solid/pane-registry), [userguide](https://github.com/solid/userguide) | Arne Hassel, Tim Berners-Lee, Vincent Tunru, Kevin Howard, Daphne |
| example applications | [profile-viewer-react](https://github.com/solid/profile-viewer-react), [solid-connections-ui](https://github.com/solid/solid-connections-ui), [solid-profile-ui](https://github.com/solid/solid-profile-ui), [solid-dashboard-ui](https://github.com/solid/solid-dashboard-ui), [solid-signup-ui](https://github.com/solid/solid-signup-ui), [solid-signin-ui](https://github.com/solid/solid-signin-ui), [solid-sign-up](https://github.com/solid/solid-sign-up), [solid zagel](https://github.com/solid/solid-zagel) | 
| a way to take data from gitter chat and move it into Solid | [gitter-solid](https://github.com/solid/gitter-solid) | 

There are various Solid-related libraries mostly being led by [Ruben Verborgh](https://github.com/RubenVerborgh). 

| Description | Associated Repositories | 
| ------------- | ------------- | 
| An archive of built versions of various Solid-related libraries | [releases](https://github.com/solid/releases) | 
| authentication tools | [solid-auth-client](https://github.com/solid/solid-auth-client), [solid-auth-oidc](https://github.com/solid/solid-auth-oidc), [solid-auth-tls](https://github.com/solid/solid-auth-tls), [oidc-auth-manager](https://github.com/solid/oidc-auth-manager), [solid-cli](https://github.com/solid/solid-cli), [solid-client](https://github.com/solid/solid-client), [solid-multi-rp-client](https://github.com/solid/solid-multi-rp-client), [oidc-web](https://github.com/solid/oidc-web), [oidc-op](https://github.com/solid/oidc-op), [oidc-rp](https://github.com/solid/oidc-rp)[oidc-rs](https://github.com/solid/oidc-rs), [keychain](https://github.com/solid/keychain), [jose](https://github.com/solid/jose), [wac-allow](https://github.com/solid/wac-allow) | 
| authorisation tools | [acl-check](https://github.com/solid/acl-check), [solid-permissions](https://github.com/solid/solid-permissions) | 
| client-side libraries | [react-components](https://github.com/solid/react-components), [form-playground](https://github.com/solid/form-playground)  | 
| querying tools | [query-ldflex](https://github.com/solid/query-ldflex), [ldflex-playground](https://github.com/solid/ldflex-playground), [solid-tpf](https://github.com/solid/solid-tpf)| 
| a description of one way to implement the specification | [solid-architecture](https://github.com/solid/solid-architecture) | 

Folllowing is a list of other Solid research: 

- [solid-email](https://github.com/solid/solid-email)
- [ldp-glob](https://github.com/solid/ldp-glob)
- [test-idp](https://github.com/solid/test-idp)
- [solid-takeout-import](https://github.com/solid/solid-takeout-import) 
- [solid-inbox](https://github.com/solid/solid-inbox)
- [kvplus-files](https://github.com/solid/kvplus-files)
- [mavo-solid](https://github.com/solid/mavo-solid)
- [solid-web-client](https://github.com/solid/solid-web-client)
- [solid-notifications](https://github.com/solid/solid-notifications)
- [resource-access](https://github.com/solid/resource-access)
- [solid platform](https://github.com/solid/solid-platform)
- [solid signup](https://github.com/solid/solid-signup)

**Comment by michielbdejong** [comment]
> aims within github.com/solid including: administration of solid properties, standardisation work, and creating and maintaining the website solidproject.org

I see github.com/solid as an open source project.
_(ducks...)_

**Comment by michielbdejong** [comment]
Just had a chat with Mitzi, we agreed that the code repos can stay under github.com/solid, but we'll look for a way to clearly label a list of "code" repos that are still maintained, and we can clean up the ones that nobody is working on anymore.

**Comment by RubenVerborgh** [comment]
> clearly label a list of "code" repos

Would tags help?

Here's how I find my slides, for instance: https://github.com/search?q=%23solid+%23slides

**Comment by michielbdejong** [comment]
Yes! We can just give every repo a 'solid' tag and then use an additional tag 'code' for the ones that contain code.

**Comment by justinwb** [comment]
A few questions for you @Mitzi-Laszlo  to make sure I'm understanding the proposal correctly:

- The first table seems to be a list of repositories that are proposed for archival, because of the "what needs to happen before archival" column heading. Is that accurate?
- Are the items in the "where this is now taking place" column where you are proposing any substantive materials be moved to? If so it should probably read something more along the lines of "should relocate to".
- Included in that list are active repositories like solid/vocab, solid/web-access-control-spec, solid/solid.mit.edu, solid/webid-oidc-spec. There are efforts underway to replace the specs with normative text and move them into the specification, but there is likely to need to be a bit more coordinated effort on those specifically beyond moving issues and pulls since better normative text doesn't exist _yet_ somewhere else. solid.mit.edu website will probably need to remain until/unless there's a decision to retire that and redirect to solidproject.org.
- Are the items in the tables of the Solid Research section only being proposed to be tagged/categorized?

**Comment by Mitzi-Laszlo** [comment]
@justinwb 

- yes

- yes 

- ok, let's add solid/vocab, solid/web-access-control-spec, solid/webid-oidc-spec to the research tag list.   solid/solid.mit.edu is no longer linked to solid.mit.edu. 

- yes

**Comment by Mitzi-Laszlo** [comment]
Following the implementation of the suggestions above here's an [update of the repository overview of the Solid GitHub](https://github.com/solid/process/pull/172)

**Comment by megoth** [comment]
Maybe wait to close issue until we have consensus and PR is merged?
