### ISSUE TITLE
Process Needs to Represent Reality 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#214]
The process was written some months ago and here I would like to invite, particularly the editors to review the process around the specification to make sure that it accurately reflects the day to day implementation of the specification work. 

For example, the headings on the specification kanban board seem to be different from the editorial process https://github.com/solid/specification/projects/1

**Comment by csarven** [comment]
Agreed. Majority of the current text can be truncated and I'm happy to revise this comment for rough approval here before making a PR. Besides the general editorial, here is a strawman proposal covering expected quality and timeline for spec reviews that I'd like to see:

"Simple" editorial updates can be committed without PRs in both Ecosystem and Panel repositories:

Ecosystem Reviews:
* PRs require minimum 3 approvals before merging.
* If minimum number of reviews are unmet within a week and there are no significant open issues/discussion in the PR thread, PR submitter can merge at their discretion with the following exception:
* PRs entailing significant spec snapshots ie. ~(FP)WD, ~CR, ~REC, may not be merged by submitter unless minimum 3 approvals are given.

Panel Reviews:
* PRs require 3 approval before merging.
* If minimum number of reviews are unmet within a week and there are no significant open issues/discussion in the PR thread, PR submitter or a member from the Editors Team can merge at their or panel's discretion.

Proposals made by Panels to the Ecosystem follow the Ecosystem Review process as above.

**Comment by csarven** [comment]
Here is revision that removes at the discretion of submitted in favour of factoring in group meetings for objections and some quality control. The first three items apply to both Ecosystem and Panel repositories.

* "Simple" editorial updates can be committed without PRs in both Ecosystem and Panel repositories.
* PRs with minimum 3 approvals will be merged.
* At each group meeting, PRs that are open longer than a week will be reviewed, and will be merged based on group consensus (eg. no objections).
* Specs incubated in Panels are required to be PRed to the Ecosystem repository.
