### ISSUE TITLE
Record roadmap and agree on process 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#220]
There are various kanban boards, diagrams and links explaining what various parties are working on. For example, [here](https://www.w3.org/DesignIssues/diagrams/solid/2018-soild-work.svg), [here](https://github.com/solid/specification/projects/1), and [here](https://github.com/solid/process/projects/1).

There is a repository that was set up some time ago called roadmap](https://github.com/solid/roadmap) however it was not clear what the scope of that repository was or how to co-create and review what should go there. 

In this issue I propose having a conversation about how to set up the practicalities of the roadmap.  

Here is a first draft of the roadmap process proposal. 

# Roadmap 
The Solid roadmap explains the upcoming plans and needs of the various parties involved in implementing Solid. 

The [Solid specification project board](https://github.com/solid/specification/projects/1) is the best place to keep up to date on how Solid development is evolving and what is in the pipeline. The Solid roadmap is not the place to read about Solid development however, the roadmap is a place to read about the implementation of Solid. 

The [roadmap repository readme](https://github.com/solid/roadmap/blob/master/README.md) gives an overview of the categories of tasks on the roadmap. 

Each .md file on the [roadmap repository](https://github.com/solid/roadmap) defines the scope of a particular task on the roadmap and a description of the profile of a person needed to complete that task. 

Anyone can make a suggestion to the roadmap repository. Roadmap proposals are to be reviewed by Tim Berners-Lee as Director of Solid to be officially incorporated into the roadmap. 

The status of the tasks is tracked on the [roadmap kanban project board](https://github.com/solid/roadmap/projects/1) which the Solid Manager is responsible for keeping up to date.

**Comment by justinwb** [comment]
Establishing the roadmap for solid requires more strategic coordination from a small group of people on the solid team (led by Tim) to project the path of solid for the next several years. It's typically something that's quite concise in number of items, with each one being strategically impactful to the mission/purpose of solid as a whole. 

I think it's sufficient to work on a single roadmap page that lives on solidproject.org (or at least start there first). I don't know if there's a need for a dedicated github repository on top of that at this point, but we should start simple and focused and then determine whether we need more complex tracking and information management through github.
