### ISSUE TITLE
Where should I add helm charts?

### ISSUE THREAD

**Issue by ianconsolata** [solid/process#232]
We use kubernetes to run our solid servers, and I'd love to submit the helm charts we use for both NSS and CSS. Helm repositories are pretty easy to self-host out of a github repo, so I'd love to put them in a new project 'solid/charts' and serve them from there.  

https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

I'm imagining a pretty small repo like https://github.com/vmware-tanzu/helm-charts to serve as the canonical solid chart repo. We could also package up charts with each individual repo (i.e. serve the CSS charts from this repo), but having a centralized place for all charts feels cleaner to me.

**Comment by justinwb** [comment]
Hi @ianconsolata. I agree that this sounds quite useful. We're trying to limit adding anything new to the solid github organization that isn't specifically related to the specification, panel work, community properties, or a reference implementation. 

I'd recommend hosting it out of repository that you control and maintain, and then coordinate with the maintainers of css and nss about getting a link out from their documentation to your repository. It may be best received as a pull with instructions of "how to run nss/css in kubernetes", but the respective maintainers will give you the best guidance on that.

**Comment by ianconsolata** [comment]
Sounds great! We're happy to host it out of [itme](https://github.com/itme) for now. I can put some time in this week to get our charts cleaned up and a little more standardized, and I'll reach back out with PRs to the appropriate repos once done.
