### ISSUE TITLE
Rename the "master" branch to "main"

### ISSUE THREAD

**Issue by csarven** [solid/process#249]
Understandably this might be too complex and risky to do for Solid org-wide, so doing it on a repo-by-repo basis would also be a good start and help to test things out.

* Identify what might break.
* Note back references (eg. in documentation, code) that might need changing.
* Document repositories to omit, if any.
* Document how people can update their cloned repositories.
* Set a date for the announcement and send it out.
* Switch
* Update back references.

Anything else that should be recorded here?

**Comment by RubenVerborgh** [comment]
This appears to have been done.
