### ISSUE TITLE
Create a private Gitter room for Women of Solid

### ISSUE THREAD

**Issue by VirginiaBalseiro** [solid/process#250]
I am in the process of creating a new space/community for women working with/interested in Solid, with the goal is to amplify female voices in the Solid space and provide a safe space to learn and help each other. 

I believe this way we can encourage women to learn about Solid, and participate in the Solid community. Women-only spaces are important and necessary for a number of reasons, including having a safe space to have meaningful discussions that might not happen otherwise, and give priority to women's voices.

I believe having a space that belongs to us will encourage engagement and participation.

I started creating a website for it, you can have a look here where you can read more about Women of Solid: https://www.womenofsolid.org. 

I believe the Women of Solid CoC is compatible with https://github.com/solid/process/blob/master/code-of-conduct.md.

It would be great to have a private Gitter room for this group, since the idea is for newcomers to join via invite so we can prevent trolls, harassers and spammers from joining the group (which is unfortunately a common occurrence).

**Comment by justinwb** [comment]
@VirginiaBalseiro Great idea - thanks for leading the charge on this. Would solid/women be acceptable as the gitter channel ID? (When created, it would be https://gitter.im/solid/women). Feel free to suggest any alternative you might prefer better.

**Comment by VirginiaBalseiro** [comment]
Thanks @justinwb! I think https://gitter.im/solid/women-of-solid might be more specific, but https://gitter.im/solid/women is alright too :)

**Comment by justinwb** [comment]
> Thanks @justinwb! I think https://gitter.im/solid/women-of-solid might be more specific, but https://gitter.im/solid/women is alright too :)

@VirginiaBalseiro Will leave it to you to make the final determination in next response, and then I'll get it made right away 🙂

**Comment by VirginiaBalseiro** [comment]
@justinwb Let’s go with women-of-solid then! Thanks!!

**Comment by justinwb** [comment]
> @justinwb Let’s go with women-of-solid then! Thanks!!

perfect - i've initialized the channel and added you. lets confirm all is working as needed and then we can close this issue 👍

**Comment by justinwb** [comment]
Looks like all is well ✅  closing issue.
