### ISSUE TITLE
Proposal to re-establish the Solid Notifications Panel

### ISSUE THREAD

**Issue by justinwb** [solid/process#258]
As work is progressing on different pathways and options for notifications in the Solid Protocol, it seems like the timing is right to resurrect the [Solid Notifications Panel](https://github.com/solid/notifications-panel) to collaborate and advance draft specifications and implementations.

This purpose of this issue is to gauge interest in these efforts. If interested, please 👍, 👎 , or comment with additional thoughts on scope, focus, goals, or concerns.

**Comment by csarven** [comment]
Solid Notifications Panel is re-introduced with a charter in PR https://github.com/solid/process/pull/264 : https://github.com/solid/process/blob/main/notifications-panel-charter.md
