### ISSUE TITLE
Proposal: ensure the Solid GitHub organization only contains working code and up-to-date documents

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#262]
This is a proposal for the Solid Team meeting.

## Current situation

There are 149 repositories under https://github.com/solid/.
They include
- process repositories
- actively used code
- old code
- people's personal projects
- etc.

**The _majority_ of those repositories contain broken code or obsolete documents.**

## Issues with the current situation

People arriving on GitHub have no obvious way of knowing what code works and what code does not.
They do not know if they can trust documents or repositories.

As a newcomer, or even someone having spent quite some time,
it's hard to distinguish which repositories are authoritative.

This reflects badly upon Solid's reputation.

## Proposed new situation

Let us strive for https://github.com/solid/ to only contain repositories that are approved by the Solid Team.
The list can grow over time.

We would need a one-time process where we move non-approved repositories to other places.
**All existing URLs remain valid** because of automated redirects that GitHub sets up.

## Concrete implementation suggestion

Let us create two new GitHub organizations:
- https://github.com/solid-archive/ for old code and documentation
- https://github.com/solid-contrib/ for current code that is not (yet) approved

Administrator rights are assigned to the same people as for https://github.com/solid/
(Note: I have created both organizations already to avoid squatting, but they can of course still be changed.)

Then we proceed as follows:
- All archived repositories under https://github.com/solid/  are moved to https://github.com/solid-archive/
- We identify repositories that we want to approve already; they remain where they are.
- On all other repositories, we open an issue detailing the intention to move:
  - to https://github.com/solid-archive/ for old repositories
  - to https://github.com/solid-contrib/ for active repositories
  - We of course also offer people the option to move the repository to an organization of their own.
- Upon a positive reaction, we move immediately.
- Upon no reaction after a set period of time (2 weeks?), we move.
- Upon negative reaction, we bring the specific case to the Solid Team meeting to decide upon an action.

**Comment by RubenVerborgh** [comment]
Some examples of repos I created that I don't think should be under `/solid` any longer:
- https://github.com/solid/query-ldflex (experimental)
- https://github.com/solid/ldflex-playground (experimental)
- https://github.com/solid/solid-tpf (experimental and old)
- https://github.com/solid/mavo-solid (old)

**Comment by timbl** [comment]
What is wrong this proposal?  It is using a change of URI to change the status of something.  That no way to run a restaurant. The way to work is to use metadata to express the status of things: lists and tags, typically. 

It is a fallacy that a "one-time change" will be what will be needed.  Things like

- actively used code
- old code
- people's personal projects
- shared projects
- placeholders for future work

are in fact not constants but functions of time.  Tempting though it is to to make different github orgs for them, we would have to review the status of them very frequently -- particularly code that work our doesn't  that changes very fast.  Do you want a CI process which switches it to a different organization until the tests pass again?

It would fine to have the solid process in a different org to code and specs, I guess.  But code and specs overlap, as canonical implementations and tests are very close to specs.

I  counter-propose that we make and curate lists in turtle of the status of the repos, and use that to drive lists on the solid project website.   The solid org on github can drive people to that.

Yes, there are things we can archive I guess, but what about things I have put there as placeholders for people to look at, things people have picked up and need help with, things which work, things which broke, things which have been fixed, things which we will never fix but we don't know that now... 

Meanwhile we have keywords like `running code` which github turns into lists like  https://github.com/search?q=topic%3Arunning-code+org%3Asolid&type=Repositories

Counter propose we continue to use metadata to solve the problem, not changing URLs of things.

**Comment by jeff-zucker** [comment]
@timbl - If you point me to existing github lists and/or the metadata terms that would be useful, I can make a generator for these repos the way I did for people at https://jeff-zucker.solidcommunity.net/sp/ which is entirely generated from RDF.

**Comment by RubenVerborgh** [comment]
> What is wrong this proposal? It is using a change of URI to change the status of something.

With all due respect, that is not a correct characterization of my proposal.

First of all, the URIs do no change. Concretely, https://github.com/solid/query-ldflex will be perpetually reachable from that URL.

The actually proposed change is to create a grouping for Solid repositories in order to make it easier for both Solid newcomers and veterans to find working documentation and code.

Currently, the number of repositories that are _not_ working in the current Solid organization is much larger than the number of repositories that do. This reflects badly upon Solid and its community.

> I counter-propose that we make and curate lists in turtle of the status of the repos, and use that to drive lists on the solid project website. 

The issue with that solution is that it does not change the experience of people on GitHub.
And GitHub is were many search engines drive people to.

> Counter propose we continue to use metadata to solve the problem, not changing URLs of things.

I'm happy to look at different solutions, but let's correctly characterize my proposal:
to move non-official repositories into a separate organization, such that the main Solid GitHub organization only contains working code. All existing URLs keep on functioning because of redirects.

I will update the description of my proposal to reflect this.

**Comment by RubenVerborgh** [comment]
More specifically, what I want to change is this:

![image](https://user-images.githubusercontent.com/675313/129490303-36a2aa3d-70c5-4976-a1bb-48b28dd26607.png)

The endorsement of the Solid organization of a project that has not been approved by the Solid Team.
Same on npm.

Because we do not control how people get to GitHub.
They may or may not use that Turtle list, but once they are on GitHub, the UI tells them clearly that project X is part of Solid. Whereas it might never have been, or not be anymore.

It so happens that moving things on GitHub creates additional URLs—but that is a side-effect, not the goal.

**Comment by justinwb** [comment]
Generally I think this is a good direction to go, so long as the people who do want to find / work on any repositories that are moved can find them, and that shouldn't be a problem given automatic github redirects, plus any additional guidance, documentation, metadata we provide above and beyond that.

I wonder whether solid-contrib would be needed, or if that wouldn't be something that could just live under a user account of the individual working on it, or in an organization they standup, until it is submitted / approved to live under the solid org?

**Comment by RubenVerborgh** [comment]
> I wonder whether solid-contrib would be needed, or if that wouldn't be something that could just live under a user account of the individual working on it, or in an organization they standup, until it is submitted / approved to live under the solid org?

Good point indeed!

One reason was that some repositories no longer have an active owner; but I suppose we could move those to archive until they are revived.

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh I think this is a great proposal; you're right that the current arrangement causes confusion for newcomers.

**Comment by RubenVerborgh** [comment]
Based on the decision at the [previous Solid Team meeting](https://github.com/solid/team/blob/main/meetings/2022-03-09.md#github-repository-cleanup), a concrete list of steps is being proposed at https://github.com/solid/team/issues/22
