### ISSUE TITLE
Include a consequences section in Solid Code of Conduct

### ISSUE THREAD

**Issue by csarven** [solid/process#273]
What happens when someone violates the [Solid Code of Conduct](https://github.com/solid/process/blob/main/code-of-conduct.md) ?

The current Solid CoC is not clear or detailed on consequences.

See also https://github.com/w3c/PWETF/issues/193 for discussion and useful links.

**Comment by sideshowtom** [comment]
A Solid credit system could be designed with ACL's to exclude those who have transgressed, and to favor those who present the proper verifiable credentials.  Unless I misunderstood something.

**Comment by csarven** [comment]
Resolved by #275
