### ISSUE TITLE
Update text or reference to aims of the Solid Gitter channels

### ISSUE THREAD

**Issue by csarven** [solid/process#274]
The Solid Code of Conduct links to https://github.com/solid/information#connect with "defined aims of the Solid gitter channels" but the URL moved (redirects) to solid-archive repo and I can't find anything pertaining to "connect" in the README after checking the commit log. There is https://github.com/solid/process/blob/main/gitter-chat-overview.md (with outdated content) .. but I'm not sure if that's intended to be the "defined aims" after content getting reshuffled.

I think the Solid CoC need not be overly specific to Gitter (at the top of the document) and needs to be applied uniformly in the Solid community irrespective to the channels/services/applications that are being used.

**Comment by theRealImy** [comment]
Link fix is proposed in above mentioned PR.
The 'uniform application of CoC' is addressed in this issue: https://github.com/solid/deit/issues/13 (can be continued there)

**Comment by theRealImy** [comment]
Ups. I closed my PR because the previous work on this pr: https://github.com/solid/process/pull/275 solved the link and much more.

**Comment by VirginiaBalseiro** [comment]
We removed this reference in the latest version of CoC. Can this usse be closed?
