### ISSUE TITLE
Linked Data / Solid Resource Version?

### ISSUE THREAD

**Issue by danielbakas** [solid/process#313]
Hi everyone! I was curious wether this repo has any Linked Data (turtle, jsonld) or any Solid Resource equivalent versions.

I am familiar with Jeff Zucker's work (https://jeff-zucker.solidcommunity.net/sp4/) but are there any official Solid or Linked Data resources to represent these teams, people and work? 

If not, I think it would be incredibly valuable for app developers (like me) who would like to share the work you're doing, while making the data in this repo dynamic, updated and save time when having to manually transcribe it. 

If no one is working on this at this time, we could gladly volunteer for a proposal  😋

Excited to know if this could be valuable 🤗

**Comment by timea-solid** [comment]
@danielbakas Jeff's work is the work you are talking about. As a Solid member, he was spearheading this topic mostly alone. If you want to help maybe I can set up a meeting between you and @jeff-zucker.

**Comment by danielbakas** [comment]
So happy to read you @timea-solid! And I'd love to! 

I know @jeff-zucker is now busy with the web-id spec, but I'm eagerly waiting for him and Vi to finish so I can dip into this, although if there's anything I can do in the meantime I'm really interested!!! 🤩

I've been working on a sort of custom version of it which I have now rendered at https://www.semantyk.com/solid (it might take a bit to load and it will be really slow, I need to optimize it 🙈)

**Comment by jeff-zucker** [comment]
Daniel -  I am in the process of re-evaluating my role in the Solid community.  My vision is to put the structure of the Solid Project as an organization into RDF in a way that can show other organizations how they can present themselves through RDF.  Your help will be invaluable.  I need to get a few other ducks in a row first, but perhaps we can meet to discuss a game plan in early March.

**Comment by danielbakas** [comment]
That sounds perfect! I'll drop you a msg on Gitter to make it happen. Thanks so much @jeff-zucker!

**Comment by timea-solid** [comment]
The actual work is tracked I believe here:https://github.com/solid/solidproject.org/issues/582 so I will close this ticket as duplicate.
