### ISSUE TITLE
Rename repo into “governance” or “proces(ses)”

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#64]
The name “culture” does not seem to represent what we have in here; let’s use a more appropriate name. (GitHub will automatically redirect.)

**Comment by dmitrizagidulin** [comment]
👍, I was thinking the same thing.

**Comment by justinwb** [comment]
👍, also agree.

**Comment by justinwb** [comment]
Do we have any consensus within this thread on what the better option would be?

Personally I like solid/governance.

**Comment by maxidorius** [comment]
Also +1 for `solid/governance`

**Comment by justinwb** [comment]
Have received direct guidance from @timbl to rename to solid/process, so we’ll be going with that! 🙂

**Comment by justinwb** [comment]
Repository has been renamed from culture to process. Note that the solid w3c community mailing list was notified of this in advance. Github automatically redirects - everything should work fine.
